services:
  chainlit:
    container_name: chainlit-frontend
    build:
      context: .
      args:
        APP_VERSION: ${APP_VERSION:-dev-local}
    ports:
      - "5002:8001"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://127.0.0.1:5001}
      LLM_TEST_PATH: ${LLM_TEST_PATH:-/ai/query}
      DEBUG_MODE: ${DEBUG_MODE:-false}
    # If you want live-reload during dev, uncomment:
    # volumes:
    #   - ./:/app
