services:
  chainlit:
    container_name: chainlit-frontend
    build: .
    ports:
      - "8001:8001"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://hotel_rag_api:8000}
      LLM_TEST_PATH: ${LLM_TEST_PATH:-/ai/query}
      DEBUG_MODE: ${DEBUG_MODE:-false}
    # If you want live-reload during dev, uncomment:
    # volumes:
    #   - ./:/app

networks:
  default:
    external: true
    name: hotel_rag_net
